import sys
import time
print("Hello! Thank you for taking the test")
time.sleep(2)
print("Here's how you will be scored")
time.sleep(1)
print("Each question will have a rating from 1 to 10. Depending on your rating, you will be grouped into different categories. They range from Friend to Superhero")
time.sleep(3)
name = str(input("What's your name? "))
print("Nice to meet you, " + name)
time.sleep(2)
print("Let's get to know you " + name)
friendship = int(input("Rate the value of friendship on a scale of 1 to 10. "))
time.sleep(1)
family = int(input("Rate the value of family on a scale of 1 to 10"))
time.sleep(1)
life = int(input("Rate your ability to answer questions on a scale of 1 to 10"))
time.sleep(1)
happiness = int(input("Rate your happiness on a scale of 1 to 10"))
time.sleep(1)
academic = int(input("Rate you level of academics on a scale of 1 to 10"))
time.sleep(1)
sport = int(input("How many teams are you in?"))
time.sleep(1)
total = friendship + family + life + happiness + academic + sport
if (friendship + family + life + happiness + academic + sport) < 10:
    print("You are someone who is lacking that special someone of something in life. A soulshell is what you are. ")
    time.sleep(1)
    print("Thank you!")
    sys.exit()
if total > 10 and total <= 20:
    print("You are someone who is interesting, but don't know how. Take a self-discovery path.")
    time.sleep(1)
    print("Thank you!")
    sys.exit()
if total > 20 and total <= 30:
    print("You are someone who knows what they want, but not quite how they want it. Take this test again")
    time.sleep(1)
    print("Thank you!")
    sys.exit()
if total > 30 and total <= 40:
    print("You are an interesting fellow, but we can't quite determine why.")
    time.sleep(1)
    print("Thank you!")
    sys.exit()
if total > 40 and total <= 50:
    print("Wow! You're a real life superhero. We very much admire your qualities!")
    time.sleep(1)
    print("Thank you!")
    sys.exit()